services:
  - type: web
    name: transcription-backend
    env: python
    runtime: python-3.10.13
    plan: free
    region: oregon
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
